import type { Coin } from "@/types";

export const COINS: Coin[] = [
  // =============================================
  // OR - 25 pieces
  // =============================================

  // --- 1 Oz Or ---
  {
    id: "american-buffalo-1oz-or",
    name: "American Buffalo 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "USA",
    diameter_mm: 32.7,
    thickness_mm: 2.95,
    first_year: 2006,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 7.5,
    face_value: "50 USD",
    highlights: [
      "Premiere piece or US en 999.9 (4 neuf)",
      "Design inspire du nickel Buffalo de 1913",
      "Seule piece US en or pur (Eagle est en 22 carats)",
    ],
  },
  {
    id: "american-eagle-1oz-or",
    name: "American Eagle 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 33.93,
    purity: 0.9167,
    fineness: "916.7",
    country: "USA",
    diameter_mm: 32.7,
    thickness_mm: 2.87,
    first_year: 1986,
    design_type: "occasional",
    design_changes: [{ year: 2021, description: "Nouveau revers (aigle)" }],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 8,
    face_value: "50 USD",
    highlights: [
      "Alliage 22 carats (91.67% or, 3% argent, 5.33% cuivre)",
      "Poids total 33.93g pour 1oz d'or pur contenu",
      "Plus resistante aux rayures que les pieces 999.9",
      "Piece or la plus vendue aux USA",
    ],
  },
  {
    id: "britannia-1oz-or",
    name: "Britannia 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 38.61,
    thickness_mm: 2.98,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [
      { year: 2021, description: "Nouveau design securise" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "100 GBP",
    highlights: [
      "Motif de securite anti-contrefacon depuis 2021",
      "Image latente et micro-texte sur le trident",
      "Exoneree de Capital Gains Tax au Royaume-Uni",
    ],
  },
  {
    id: "kangourou-1oz-or",
    name: "Kangourou 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 32.1,
    thickness_mm: 2.65,
    first_year: 1986,
    design_type: "annual",
    design_changes: [
      { year: 1986, description: "Lancement sous le nom Nugget" },
      { year: 1989, description: "Changement pour design Kangourou" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "100 AUD",
    highlights: [
      "Design du kangourou change chaque annee",
      "Anciennement appelee 'Nugget' (1986-1989)",
      "Perth Mint garantit rachat a vie",
    ],
  },
  {
    id: "maple-leaf-1oz-or",
    name: "Maple Leaf 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 30.0,
    thickness_mm: 2.87,
    first_year: 1979,
    design_type: "occasional",
    design_changes: [
      { year: 2013, description: "Ajout micro-gravure securite" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "50 CAD",
    highlights: [
      "Premiere piece bullion 999.9 au monde (1982)",
      "Micro-gravure laser d'une feuille d'erable (visible a la loupe)",
      "Lignes radiales anti-contrefacon depuis 2013",
      "Une des pieces les plus pures du marche",
    ],
  },
  {
    id: "philharmonique-1oz-or",
    name: "Philharmonique 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 37.0,
    thickness_mm: 2.0,
    first_year: 1989,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "100 EUR",
    highlights: [
      "Seule piece bullion majeure en euros",
      "Pas de portrait de monarque (instruments de musique)",
      "Design inchange depuis 1989",
      "Piece or la plus vendue en Europe",
    ],
  },
  {
    id: "krugerrand-1oz-or",
    name: "Krugerrand 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 33.93,
    purity: 0.9167,
    fineness: "916.7",
    country: "Afrique du Sud",
    diameter_mm: 32.77,
    thickness_mm: 2.84,
    first_year: 1967,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 7,
    face_value: null,
    mintage: "44 556 584",
    highlights: [
      "Premiere piece bullion moderne au monde (1967)",
      "Aucune valeur faciale inscrite",
      "Alliage 22 carats avec cuivre (couleur orangee)",
      "Plus de 50 millions d'unites produites",
      "Design inchange depuis 1967",
    ],
  },

  // --- 1/2 Oz Or ---
  {
    id: "britannia-1-2oz-or",
    name: "Britannia 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 27.0,
    thickness_mm: 2.1,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 11,
    face_value: "50 GBP",
    highlights: [
      "Securite anti-contrefacon comme la version 1 Oz",
      "Bon compromis poids/prime pour investir",
      "Exoneree de Capital Gains Tax au Royaume-Uni",
    ],
  },
  {
    id: "kangourou-1-2oz-or",
    name: "Kangourou 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 25.1,
    thickness_mm: 2.35,
    first_year: 1986,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 10,
    face_value: "50 AUD",
    highlights: [
      "Design du kangourou change chaque annee",
      "Perth Mint garantit rachat a vie",
      "Bon compromis poids/prime pour investir",
    ],
  },
  {
    id: "maple-leaf-1-2oz-or",
    name: "Maple Leaf 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 25.0,
    thickness_mm: 2.23,
    first_year: 1986,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "25 CAD",
    highlights: [
      "Purete 999.9, lignee de la premiere piece bullion 4 neuf",
      "Micro-gravure laser anti-contrefacon",
      "Bon compromis poids/prime pour investir",
    ],
  },
  {
    id: "philharmonique-1-2oz-or",
    name: "Philharmonique 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 28.0,
    thickness_mm: 1.6,
    first_year: 1994,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 9,
    face_value: "50 EUR",
    highlights: [
      "Seule piece bullion majeure en euros",
      "Design inchange depuis 1989",
      "Bon compromis poids/prime pour investir",
    ],
  },

  // --- 1/4 Oz Or ---
  {
    id: "britannia-1-4oz-or",
    name: "Britannia 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 22.0,
    thickness_mm: 1.7,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 13,
    face_value: "25 GBP",
    highlights: [
      "Securite anti-contrefacon comme la version 1 Oz",
      "Ticket d'entree accessible pour investir dans l'or",
      "Exoneree de Capital Gains Tax au Royaume-Uni",
    ],
  },
  {
    id: "kangourou-1-4oz-or",
    name: "Kangourou 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 20.1,
    thickness_mm: 1.9,
    first_year: 1986,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 14,
    face_value: "25 AUD",
    highlights: [
      "Design du kangourou change chaque annee",
      "Perth Mint garantit rachat a vie",
      "Ticket d'entree accessible pour investir dans l'or",
    ],
  },
  {
    id: "maple-leaf-1-4oz-or",
    name: "Maple Leaf 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 20.0,
    thickness_mm: 1.78,
    first_year: 1982,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: "10 CAD",
    highlights: [
      "Purete 999.9, micro-gravure laser anti-contrefacon",
      "Ticket d'entree accessible pour investir dans l'or",
      "Une des pieces les plus pures du marche",
    ],
  },
  {
    id: "philharmonique-1-4oz-or",
    name: "Philharmonique 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 22.0,
    thickness_mm: 1.2,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: "25 EUR",
    highlights: [
      "Seule piece bullion majeure en euros",
      "Design inchange depuis 1989",
      "Ticket d'entree accessible pour investir dans l'or",
    ],
  },

  // --- 1/10 Oz Or ---
  {
    id: "britannia-1-10oz-or",
    name: "Britannia 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 16.5,
    thickness_mm: 1.3,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 21,
    face_value: "10 GBP",
    highlights: [
      "Securite anti-contrefacon comme la version 1 Oz",
      "Format compact ideal pour offrir",
      "Exoneree de Capital Gains Tax au Royaume-Uni",
    ],
  },
  {
    id: "kangourou-1-10oz-or",
    name: "Kangourou 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 16.1,
    thickness_mm: 1.4,
    first_year: 1986,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 20,
    face_value: "15 AUD",
    highlights: [
      "Design du kangourou change chaque annee",
      "Perth Mint garantit rachat a vie",
      "Format compact ideal pour offrir",
    ],
  },
  {
    id: "maple-leaf-1-10oz-or",
    name: "Maple Leaf 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 16.0,
    thickness_mm: 1.22,
    first_year: 1982,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 18,
    face_value: "5 CAD",
    highlights: [
      "Purete 999.9, micro-gravure laser anti-contrefacon",
      "Format compact ideal pour offrir",
      "Une des pieces les plus pures du marche",
    ],
  },
  {
    id: "philharmonique-1-10oz-or",
    name: "Philharmonique 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 16.0,
    thickness_mm: 0.9,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 18,
    face_value: "10 EUR",
    highlights: [
      "Seule piece bullion majeure en euros",
      "Design inchange depuis 1989",
      "Format compact ideal pour offrir",
    ],
  },

  // --- Fractionnelles & Panda Or ---
  {
    id: "maple-leaf-1-20oz-or",
    name: "Maple Leaf 1/20 Oz Or",
    metal: "gold",
    weight_oz: 0.05,
    weight_g: 1.56,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 14.1,
    thickness_mm: 0.92,
    first_year: 1993,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 36,
    face_value: "1 CAD",
    highlights: [
      "Plus petite Maple Leaf disponible",
      "Prime elevee due a la taille",
      "Ideale pour cadeau ou petit budget",
    ],
  },
  {
    id: "panda-30g-or",
    name: "Panda Or 30g",
    metal: "gold",
    weight_oz: 0.9645,
    weight_g: 30.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 32.0,
    thickness_mm: 2.4,
    first_year: 1982,
    design_type: "annual",
    design_changes: [{ year: 2016, description: "Passage de 1oz a 30g" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 7,
    face_value: "500 CNY",
    highlights: [
      "Design du panda change chaque annee (tres collectionne)",
      "Passage de l'once troy (31.1g) au gramme (30g) en 2016",
      "Seule piece bullion majeure en grammes",
      "Tres populaire aupres des collectionneurs asiatiques",
    ],
  },
  {
    id: "panda-15g-or",
    name: "Panda Or 15g",
    metal: "gold",
    weight_oz: 0.4823,
    weight_g: 15.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 27.0,
    thickness_mm: 1.85,
    first_year: 1982,
    design_type: "annual",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "200 CNY",
    highlights: [
      "Design du panda change chaque annee (tres collectionne)",
      "Poids en grammes (standard chinois depuis 2016)",
      "Tres populaire aupres des collectionneurs asiatiques",
    ],
  },
  {
    id: "panda-8g-or",
    name: "Panda Or 8g",
    metal: "gold",
    weight_oz: 0.2572,
    weight_g: 8.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 22.0,
    thickness_mm: 1.5,
    first_year: 1982,
    design_type: "annual",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 13,
    face_value: "100 CNY",
    highlights: [
      "Design du panda change chaque annee (tres collectionne)",
      "Plus petit format Panda or, ticket d'entree accessible",
      "Poids en grammes (standard chinois depuis 2016)",
    ],
  },

  // --- Pieces classiques cotees ---
  {
    id: "napoleon-20f-or",
    name: "Napoleon 20 Francs Or",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.45,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 21.0,
    thickness_mm: 1.3,
    first_year: 1803,
    design_type: "occasional",
    design_changes: [
      { year: 1803, description: "Napoleon Empereur" },
      { year: 1807, description: "Tete lauree" },
      { year: 1852, description: "Napoleon III" },
      { year: 1899, description: "Marianne Coq" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6,
    face_value: "20 FRF",
    highlights: [
      "Piece d'or francaise la plus echangee",
      "Cotation quotidienne (CPoR Devises)",
      "Nombreuses variantes (Coq, Napoleon III, etc.)",
      "Exoneree de TVA et plus-values apres 22 ans",
      "Format standardise de l'Union Latine",
    ],
  },
  {
    id: "souverain-or",
    name: "Souverain Or",
    metal: "gold",
    weight_oz: 0.2354,
    weight_g: 7.98,
    purity: 0.9167,
    fineness: "916.7",
    country: "Royaume-Uni",
    diameter_mm: 22.05,
    thickness_mm: 1.52,
    first_year: 1817,
    design_type: "occasional",
    design_changes: [
      { year: 1817, description: "George III" },
      { year: 1893, description: "Victoria Old Head" },
      { year: 1902, description: "Edward VII" },
      { year: 1911, description: "George V" },
      { year: 1937, description: "George VI" },
      { year: 1957, description: "Elizabeth II" },
      { year: 2023, description: "Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 8,
    face_value: "1 GBP",
    highlights: [
      "Plus de 200 ans d'histoire",
      "Design Saint-Georges terrassant le dragon",
      "Nombreux millesimes et ateliers de frappe",
      "Exoneree de CGT au Royaume-Uni",
      "Tres liquide sur le marche europeen",
    ],
  },
  {
    id: "20-francs-suisse-or",
    name: "20 Francs Suisse Or (Vreneli)",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.45,
    purity: 0.9,
    fineness: "900",
    country: "Suisse",
    diameter_mm: 21.0,
    thickness_mm: 1.25,
    first_year: 1897,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6,
    face_value: "20 CHF",
    mintage: "58 900 000",
    highlights: [
      "Surnommee 'Vreneli' (petit visage de femme)",
      "Meme poids et titre que le Napoleon 20F",
      "Membre de l'Union Latine (interchangeable)",
      "Faible prime, excellente liquidite",
    ],
  },

  // --- Pieces historiques / semi-numismatiques ---
  {
    id: "10-francs-napoleon-or",
    name: "10 Francs Napoleon (Demi Napoleon)",
    metal: "gold",
    weight_oz: 0.0933,
    weight_g: 3.2258,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 19,
    thickness_mm: 0.8,
    first_year: 1850,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 25,
    face_value: "10 FRF",
    mintage: "23 680 424",
    highlights: [
      "Demi-Napoleon : moitie exacte du Napoleon 20F (2.90g d'or fin)",
      "Piece d'or francaise la plus accessible en budget",
      "Rarete croissante : exemplaires en bon etat tres recherches",
    ],
  },
  {
    id: "10-francs-marianne-coq-or",
    name: "10 Francs Marianne Coq Or",
    metal: "gold",
    weight_oz: 0.0933,
    weight_g: 3.2258,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 19,
    thickness_mm: 0.86,
    first_year: 1899,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 25,
    face_value: "10 FRF",
    mintage: "23 866 852",
    highlights: [
      "Design Chaplain (Marianne / Coq gaulois) de la IIIe Republique",
      "Variante la moins chere au gramme parmi les 10 Francs or",
      "Frappee a Paris entre 1899 et 1914",
    ],
  },
  {
    id: "20-francs-marianne-coq-or",
    name: "20 Francs Marianne Coq Or",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.4516,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 21,
    thickness_mm: 1.31,
    first_year: 1898,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6,
    face_value: "20 FRF",
    mintage: "117 000 000",
    highlights: [
      "Le Napoleon par excellence, piece d'or francaise la plus echangee",
      "Tirage massif (117M), prime faible",
      "Design iconique de Chaplain : Marianne et Coq gaulois",
    ],
  },
  {
    id: "union-latine-or",
    name: "Union Latine 20 Francs Or",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.4516,
    purity: 0.9,
    fineness: "900",
    country: "Europe (Union Latine)",
    diameter_mm: 21,
    thickness_mm: 1.31,
    first_year: 1865,
    design_type: "occasional",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 6,
    face_value: "20 Francs (ou equivalent)",
    highlights: [
      "Ancetre de l'euro : monnaie commune frappee par 15+ pays",
      "Memes specs que le Napoleon 20F (6.45g, 900 milliemes)",
      "Effigies variees (Vreneli, Leopold, Umberto, etc.)",
    ],
  },
  {
    id: "louis-dor-20-francs-or",
    name: "Louis d'Or 20 Francs",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.4516,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 21,
    thickness_mm: 1.31,
    first_year: 1803,
    design_type: "occasional",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 7,
    face_value: "20 FRF",
    highlights: [
      "Cree par Napoleon Bonaparte en 1803, successeur des anciens Louis d'or royaux",
      "Socle de l'Union Latine et etalon-or europeen",
      "Multiples effigies : Napoleon Ier, Louis XVIII, Charles X, Louis-Philippe, Napoleon III",
    ],
  },
  {
    id: "50-francs-napoleon-iii-or",
    name: "50 Francs Napoleon III Or",
    metal: "gold",
    weight_oz: 0.4667,
    weight_g: 16.129,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 28,
    thickness_mm: 1.85,
    first_year: 1855,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 20,
    face_value: "50 FRF",
    mintage: "961 959",
    highlights: [
      "Piece de prestige du Second Empire, tirage limite (~960 000)",
      "Contient 14.52g d'or pur (2.5 Napoleons 20F)",
      "Deux variantes : tete nue (1855-1860) et tete lauree (1862-1868)",
    ],
  },
  {
    id: "demi-souverain-or",
    name: "Demi-Souverain Or",
    metal: "gold",
    weight_oz: 0.1177,
    weight_g: 3.994,
    purity: 0.9167,
    fineness: "916.7",
    country: "Royaume-Uni",
    diameter_mm: 19.3,
    thickness_mm: 0.99,
    first_year: 1817,
    design_type: "occasional",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "0.5 GBP",
    highlights: [
      "Moitie du Souverain : 3.99g brut, 3.66g d'or pur, or 22 carats",
      "Revers Saint-Georges terrassant le dragon (Pistrucci)",
      "Exoneree de CGT au Royaume-Uni (legal tender)",
    ],
  },
  {
    id: "demi-souverain-elisabeth-ii-or",
    name: "Demi-Souverain Elisabeth II Or",
    metal: "gold",
    weight_oz: 0.1177,
    weight_g: 3.994,
    purity: 0.9167,
    fineness: "916.7",
    country: "Royaume-Uni",
    diameter_mm: 19.3,
    thickness_mm: 0.99,
    first_year: 1957,
    design_type: "occasional",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "0.5 GBP",
    highlights: [
      "Memes specs que le demi-souverain classique, portrait Elisabeth II",
      "Frappes modernes bullion et proof par la Royal Mint",
      "Tres appreciee en Europe et au Moyen-Orient",
    ],
  },
  {
    id: "5-dollars-us-or",
    name: "5 Dollars US Or (Half Eagle)",
    metal: "gold",
    weight_oz: 0.2419,
    weight_g: 8.359,
    purity: 0.9,
    fineness: "900",
    country: "USA",
    diameter_mm: 21.6,
    thickness_mm: 1.59,
    first_year: 1839,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: "5 USD",
    highlights: [
      "Half Eagle pre-1933, 0.2419 oz d'or pur",
      "Designs Liberty Head (1839-1908) et Indian Head incuse (1908-1929)",
      "Piece recherchee par collectionneurs US et europeens",
    ],
  },
  {
    id: "10-dollars-us-or",
    name: "10 Dollars US Or (Eagle)",
    metal: "gold",
    weight_oz: 0.4838,
    weight_g: 16.718,
    purity: 0.9,
    fineness: "900",
    country: "USA",
    diameter_mm: 27,
    thickness_mm: 2.03,
    first_year: 1838,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "10 USD",
    highlights: [
      "Eagle pre-1933, pres d'une demi-once d'or pur (0.4838 oz)",
      "Indian Head Eagle (1907-1933) par Saint-Gaudens, design iconique",
      "Piece historique de l'ere de l'etalon-or americain",
    ],
  },
  {
    id: "20-dollars-us-or",
    name: "20 Dollars US Or (Double Eagle)",
    metal: "gold",
    weight_oz: 0.9675,
    weight_g: 33.436,
    purity: 0.9,
    fineness: "900",
    country: "USA",
    diameter_mm: 34,
    thickness_mm: 2.41,
    first_year: 1850,
    design_type: "occasional",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: "20 USD",
    highlights: [
      "Double Eagle : pres d'une once d'or pur (0.9675 oz, 30.09g)",
      "Le Saint-Gaudens (1907-1933) considere comme la plus belle piece d'or jamais frappee",
      "Nee de la Ruee vers l'or californienne (1849)",
    ],
  },
  {
    id: "50-pesos-or",
    name: "50 Pesos Mexicains Or (Centenario)",
    metal: "gold",
    weight_oz: 1.2057,
    weight_g: 41.667,
    purity: 0.9,
    fineness: "900",
    country: "Mexique",
    diameter_mm: 37,
    thickness_mm: 2.69,
    first_year: 1921,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 5,
    face_value: "50 MXN",
    highlights: [
      "L'une des plus grandes pieces d'or : 41.67g brut, 37.50g d'or pur (1.2057 oz)",
      "Design spectaculaire avec l'Ange de l'Independance",
      "Millions de refrappes datees 1947, prime faible",
    ],
  },
  {
    id: "4-ducats-or",
    name: "4 Ducats Or (Autriche)",
    metal: "gold",
    weight_oz: 0.443,
    weight_g: 13.9636,
    purity: 0.986,
    fineness: "986",
    country: "Autriche",
    diameter_mm: 40,
    thickness_mm: 0.7,
    first_year: 1872,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 8,
    face_value: "4 Ducats",
    highlights: [
      "Purete exceptionnelle 98.6% (23.75 carats)",
      "Format unique : 40mm de diametre, seulement 0.7mm d'epaisseur",
      "Portrait Francois-Joseph Ier, refrappes officielles datees 1915",
    ],
  },
  {
    id: "1-ducat-or",
    name: "1 Ducat Or (Francois-Joseph 1915)",
    metal: "gold",
    weight_oz: 0.1107,
    weight_g: 3.4909,
    purity: 0.986,
    fineness: "986",
    country: "Autriche",
    diameter_mm: 20,
    thickness_mm: 0.8,
    first_year: 1872,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 8,
    face_value: "1 Ducat",
    highlights: [
      "Or 98.6% (23.75 carats), 3.44g d'or fin",
      "Refrappes officielles datees 1915 par la Monnaie d'Autriche",
      "Format miniature (20mm), accessible pour petit budget",
    ],
  },
  {
    id: "100-corona-or",
    name: "100 Corona Or (Francois-Joseph 1915)",
    metal: "gold",
    weight_oz: 0.9802,
    weight_g: 33.8753,
    purity: 0.9,
    fineness: "900",
    country: "Autriche",
    diameter_mm: 37,
    thickness_mm: 2.3,
    first_year: 1908,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 4,
    face_value: "100 Corona",
    highlights: [
      "Pres d'une once d'or pur (0.9802 oz, 30.49g)",
      "Alternative historique au Krugerrand (refrappes depuis 1975)",
      "Prime tres faible, piece bullion par excellence en Europe",
    ],
  },
  {
    id: "20-reichsmarks-or",
    name: "20 Reichsmarks Or",
    metal: "gold",
    weight_oz: 0.2305,
    weight_g: 7.965,
    purity: 0.9,
    fineness: "900",
    country: "Allemagne",
    diameter_mm: 22.5,
    thickness_mm: 1.0,
    first_year: 1871,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "20 Mark",
    highlights: [
      "Alter ego allemand du Napoleon 20F, plus d'or fin par unite (7.17g vs 5.81g)",
      "Frappee sous l'Empire allemand (1871-1915), effigie Wilhelm II",
      "Pas de refrappes, offre limitee, interet numismatique croissant",
    ],
  },
  {
    id: "20-francs-tunisie-or",
    name: "20 Francs Tunisie Or",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.4516,
    purity: 0.9,
    fineness: "900",
    country: "Tunisie",
    diameter_mm: 21,
    thickness_mm: 1.3,
    first_year: 1891,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 10,
    face_value: "20 Francs",
    highlights: [
      "Memes specs que le Napoleon 20F (Union Latine)",
      "Inscriptions en arabe, originalite culturelle unique",
      "Plus rare que les pieces francaises equivalentes",
    ],
  },
  {
    id: "10-florins-or",
    name: "10 Florins Or (Pays-Bas)",
    metal: "gold",
    weight_oz: 0.1947,
    weight_g: 6.729,
    purity: 0.9,
    fineness: "900",
    country: "Pays-Bas",
    diameter_mm: 22,
    thickness_mm: 1.3,
    first_year: 1818,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 10,
    face_value: "10 Guilders",
    highlights: [
      "Piece d'or neerlandaise contenant 6.06g d'or pur",
      "Portraits Guillaume III et Reine Wilhelmina",
      "Production arretee, pas de refrappes, offre limitee",
    ],
  },
  {
    id: "100-kurush-or",
    name: "100 Kurush Or (Empire Ottoman/Turquie)",
    metal: "gold",
    weight_oz: 0.2127,
    weight_g: 7.216,
    purity: 0.9167,
    fineness: "916.7",
    country: "Turquie",
    diameter_mm: 22.3,
    thickness_mm: 1.4,
    first_year: 1844,
    design_type: "occasional",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 10,
    face_value: "100 Kurush",
    highlights: [
      "Or 22 carats (91.67%), 6.61g d'or pur, heritage Ottoman",
      "Calligraphie islamique et tughra (sceau du sultan)",
      "Toujours legal tender en Turquie, marche actif",
    ],
  },

  // --- Zodiac Monnaie de Paris & Austerlitz ---
  {
    id: "zodiac-taureau-2026-or",
    name: "Zodiaque Taureau 2026 Or",
    metal: "gold",
    weight_oz: 0.0161,
    weight_g: 0.5,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 11,
    thickness_mm: 0.5,
    first_year: 2026,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 150,
    face_value: "5 EUR",
    mintage: "2 026",
    highlights: [
      "Micro-piece or 999 milliemes frappee par la Monnaie de Paris",
      "Qualite Belle Epreuve (BE), tirage 2 026 exemplaires",
      "Collection Astro 2026, forte valeur collectible",
    ],
  },
  {
    id: "zodiac-gemeaux-2026-or",
    name: "Zodiaque Gemeaux 2026 Or",
    metal: "gold",
    weight_oz: 0.0161,
    weight_g: 0.5,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 11,
    thickness_mm: 0.5,
    first_year: 2026,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 150,
    face_value: "5 EUR",
    mintage: "2 026",
    highlights: [
      "Or pur 999 milliemes, collection Astro Monnaie de Paris",
      "Tirage strictement limite a 2 026 exemplaires",
      "Revers commun avec roue zodiacale des 12 signes",
    ],
  },
  {
    id: "zodiac-cancer-2026-or",
    name: "Zodiaque Cancer 2026 Or",
    metal: "gold",
    weight_oz: 0.0161,
    weight_g: 0.5,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 11,
    thickness_mm: 0.5,
    first_year: 2026,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 150,
    face_value: "5 EUR",
    mintage: "2 026",
    highlights: [
      "Or fin 999, collection Astro 2026 Monnaie de Paris",
      "Design du Cancer (signe d'eau), qualite Belle Epreuve",
      "Tirage limite a 2 026 exemplaires",
    ],
  },
  {
    id: "zodiac-lion-2026-or",
    name: "Zodiaque Lion 2026 Or",
    metal: "gold",
    weight_oz: 0.0161,
    weight_g: 0.5,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 11,
    thickness_mm: 0.5,
    first_year: 2026,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 150,
    face_value: "5 EUR",
    mintage: "2 026",
    highlights: [
      "Or fin 999 milliemes, qualite Belle Epreuve",
      "Design du Lion (signe de feu), Monnaie de Paris",
      "Tirage 2 026 exemplaires, premiere edition or Astro",
    ],
  },
  {
    id: "zodiac-vierge-2026-or",
    name: "Zodiaque Vierge 2026 Or",
    metal: "gold",
    weight_oz: 0.0161,
    weight_g: 0.5,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 11,
    thickness_mm: 0.5,
    first_year: 2026,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 150,
    face_value: "5 EUR",
    mintage: "2 026",
    highlights: [
      "Or pur 999 milliemes, frappe Belle Epreuve Monnaie de Paris",
      "Design de la Vierge (signe de terre), tirage 2 026 ex.",
      "Piece miniature (11mm) avec constellation en arriere-plan",
    ],
  },
  {
    id: "zodiac-balance-2026-or",
    name: "Zodiaque Balance 2026 Or",
    metal: "gold",
    weight_oz: 0.0161,
    weight_g: 0.5,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 11,
    thickness_mm: 0.5,
    first_year: 2026,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 150,
    face_value: "5 EUR",
    mintage: "2 026",
    highlights: [
      "Or fin 999 milliemes, qualite Belle Epreuve",
      "Design de la Balance (signe d'air), Monnaie de Paris",
      "Premiere edition or de la collection Astro, tirage 2 026 ex.",
    ],
  },
  {
    id: "zodiac-sagittaire-2026-or",
    name: "Zodiaque Sagittaire 2026 Or",
    metal: "gold",
    weight_oz: 0.0161,
    weight_g: 0.5,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 11,
    thickness_mm: 0.5,
    first_year: 2026,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 150,
    face_value: "5 EUR",
    mintage: "2 026",
    highlights: [
      "Or pur 999, frappe Belle Epreuve Monnaie de Paris",
      "Design du Sagittaire (signe de feu), tirage 2 026 ex.",
      "Collection Astro 2026, forte valeur collectible",
    ],
  },
  {
    id: "austerlitz-2025-or",
    name: "Austerlitz 1805-2025 Or (Monnaie de Paris)",
    metal: "gold",
    weight_oz: 0.2572,
    weight_g: 8,
    purity: 0.999,
    fineness: "999",
    country: "France",
    diameter_mm: 29,
    thickness_mm: 1.5,
    first_year: 2025,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 80,
    face_value: "1 000 EUR",
    mintage: "2 025",
    highlights: [
      "220e anniversaire de la bataille d'Austerlitz (2 decembre 1805)",
      "Valeur faciale 1 000 EUR, 8g or fin 999, qualite BU",
      "Tirage 2 025 exemplaires, gravure Joaquin Jimenez",
    ],
  },

  // --- Panda Or 3g ---
  {
    id: "panda-3g-or",
    name: "Panda Or 3g",
    metal: "gold",
    weight_oz: 0.0964,
    weight_g: 3,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 18,
    thickness_mm: 1.05,
    first_year: 2016,
    design_type: "annual",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 25,
    face_value: "50 CNY",
    mintage: "600 000",
    highlights: [
      "Plus petite fraction du Panda or (hors 1g), point d'entree abordable",
      "Design change chaque annee, forte valeur collectible",
      "Premium eleve mais forte demande collectionneurs",
    ],
  },

  // --- Libertad Or (Mexique) ---
  {
    id: "libertad-1oz-or",
    name: "Libertad 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 34.5,
    thickness_mm: 2.69,
    first_year: 1981,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: null,
    highlights: [
      "Frappee par Casa de Moneda de Mexico (plus vieille menthe des Ameriques)",
      "Design iconique : Victoire Ailee + volcans Popocatepetl et Iztaccihuatl",
      "Pas de valeur faciale (cours legal sans denomination)",
      "Tirage limite, plus rare que Maple Leaf ou Eagle",
    ],
  },
  {
    id: "libertad-1-2oz-or",
    name: "Libertad 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.5517,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 29.0,
    thickness_mm: 2.17,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: null,
    highlights: [
      "Format fractionnel populaire",
      "Meme design que la 1oz",
      "Tirage tres limite",
    ],
  },
  {
    id: "libertad-1-4oz-or",
    name: "Libertad 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.7758,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 23.0,
    thickness_mm: 1.78,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 18,
    face_value: null,
    highlights: [
      "Petit format accessible",
      "Prime plus elevee que les 1oz",
      "Collectionnee pour sa rarete",
    ],
  },
  {
    id: "libertad-1-10oz-or",
    name: "Libertad 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.1103,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 16.0,
    thickness_mm: 1.19,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 25,
    face_value: null,
    highlights: [
      "Format ideal pour debuter",
      "Prime elevee sur petits formats",
      "Tres recherchee des collectionneurs",
    ],
  },
  {
    id: "libertad-1-20oz-or",
    name: "Libertad 1/20 Oz Or",
    metal: "gold",
    weight_oz: 0.05,
    weight_g: 1.5551,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 13.0,
    thickness_mm: 0.85,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: null,
    highlights: [
      "Plus petite Libertad or disponible",
      "Prime tres elevee",
      "Plutot pour collectionneurs que investisseurs",
    ],
  },

  // =============================================
  // ARGENT - 25 pieces
  // =============================================

  // --- 1 Oz Argent bullion moderne ---
  {
    id: "maple-leaf-1oz-argent",
    name: "Maple Leaf 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 38.0,
    thickness_mm: 3.29,
    first_year: 1988,
    design_type: "occasional",
    design_changes: [
      { year: 2014, description: "Ajout micro-gravure securite" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: "5 CAD",
    highlights: [
      "Purete 999.9 (4 neuf) - la plus pure du marche",
      "Micro-gravure laser et lignes radiales anti-contrefacon",
      "Une des pieces argent les plus vendues au monde",
    ],
  },
  {
    id: "philharmonique-1oz-argent",
    name: "Vienna Philharmonic 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Autriche",
    diameter_mm: 37.0,
    thickness_mm: 3.2,
    first_year: 2008,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 34,
    face_value: "1.50 EUR",
    highlights: [
      "Version argent lancee en 2008 (or depuis 1989)",
      "Seule piece bullion argent en euros",
      "Design identique a la version or",
    ],
  },
  {
    id: "kangourou-1oz-argent",
    name: "Kangourou 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 40.6,
    thickness_mm: 4.0,
    first_year: 2016,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: "1 AUD",
    highlights: [
      "Lancee en 2016 (plus recente que la version or)",
      "Design du kangourou change chaque annee",
      "Purete 999.9 comme la Maple Leaf",
    ],
  },
  {
    id: "britannia-1oz-argent",
    name: "Britannia 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Royaume-Uni",
    diameter_mm: 38.61,
    thickness_mm: 3.0,
    first_year: 1997,
    design_type: "occasional",
    design_changes: [
      { year: 2021, description: "Nouveau design securise" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 34,
    face_value: "2 GBP",
    highlights: [
      "Elements de securite avances depuis 2021",
      "Image latente et micro-texte sur le trident",
      "Exoneree de CGT au Royaume-Uni",
    ],
  },
  {
    id: "american-eagle-1oz-argent",
    name: "American Eagle 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "USA",
    diameter_mm: 40.6,
    thickness_mm: 2.98,
    first_year: 1986,
    design_type: "occasional",
    design_changes: [{ year: 2021, description: "Nouveau revers (aigle)" }],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 38,
    face_value: "1 USD",
    highlights: [
      "Piece argent la plus vendue au monde",
      "Design Walking Liberty (avers) depuis 1986",
      "Nouveau revers avec aigle en vol depuis 2021",
      "Prime plus elevee que les concurrentes",
    ],
  },
  {
    id: "krugerrand-1oz-argent",
    name: "Krugerrand 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Afrique du Sud",
    diameter_mm: 38.725,
    thickness_mm: 3.0,
    first_year: 2017,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 33,
    face_value: null,
    highlights: [
      "Lancee en 2017 pour les 50 ans du Krugerrand or",
      "Meme design que la version or",
      "Pas de valeur faciale (comme la version or)",
    ],
  },
  {
    id: "panda-30g-argent",
    name: "China Panda 30g Argent",
    metal: "silver",
    weight_oz: 0.9645,
    weight_g: 30.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 40.0,
    thickness_mm: 2.98,
    first_year: 1983,
    design_type: "annual",
    design_changes: [{ year: 2016, description: "Passage de 1oz a 30g" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 38,
    face_value: "10 CNY",
    highlights: [
      "Design du panda change chaque annee",
      "Passage de 1oz a 30g en 2016",
      "Tres recherchee par les collectionneurs",
    ],
  },
  {
    id: "kookaburra-1oz-argent",
    name: "Kookaburra 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Australie",
    diameter_mm: 40.6,
    thickness_mm: 4.0,
    first_year: 1990,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 43,
    face_value: "1 AUD",
    highlights: [
      "Design du martin-chasseur change chaque annee",
      "Premiere piece australienne a design annuel",
      "Tirages limites (collectionnee par millesime)",
    ],
  },
  {
    id: "koala-1oz-argent",
    name: "Koala 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Australie",
    diameter_mm: 40.6,
    thickness_mm: 4.0,
    first_year: 2007,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 43,
    face_value: "1 AUD",
    highlights: [
      "Design du koala change chaque annee",
      "Lancee en 2007 (plus recente que Kookaburra)",
      "Tirages limites, recherchee par les collectionneurs",
    ],
  },
  {
    id: "libertad-1-20oz-argent",
    name: "Libertad 1/20 Oz Argent",
    metal: "silver",
    weight_oz: 0.05,
    weight_g: 1.555,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 16.0,
    thickness_mm: 1.0,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 120,
    face_value: null,
    highlights: [
      "Plus petite Libertad disponible",
      "Tirage tres limite",
      "Prime tres elevee due a la rarete",
    ],
  },
  {
    id: "libertad-1-10oz-argent",
    name: "Libertad 1/10 Oz Argent",
    metal: "silver",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 20.0,
    thickness_mm: 1.3,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 80,
    face_value: null,
    highlights: [
      "Tirage tres limite, forte prime de rarete",
      "Ange de l'Independance au revers",
      "Aucune valeur faciale inscrite",
    ],
  },
  {
    id: "libertad-1-4oz-argent",
    name: "Libertad 1/4 Oz Argent",
    metal: "silver",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 27.0,
    thickness_mm: 2.0,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 60,
    face_value: null,
    highlights: [
      "Tirage limite, prime de rarete significative",
      "Ange de l'Independance au revers",
      "Aucune valeur faciale inscrite",
    ],
  },
  {
    id: "libertad-1-2oz-argent",
    name: "Libertad 1/2 Oz Argent",
    metal: "silver",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 33.0,
    thickness_mm: 2.5,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 50,
    face_value: null,
    highlights: [
      "Bon compromis taille/prime dans la gamme Libertad",
      "Ange de l'Independance au revers",
      "Aucune valeur faciale inscrite",
    ],
  },
  {
    id: "libertad-1oz-argent",
    name: "Libertad 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 40.0,
    thickness_mm: 3.0,
    first_year: 1982,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 45,
    face_value: null,
    highlights: [
      "Aucune valeur faciale (unique parmi les pieces bullion)",
      "Valeur legale = cours du metal (fluctue quotidiennement)",
      "Tirage tres limite (prime elevee)",
      "Design de l'Ange de l'Independance",
      "Garantie par Banco de Mexico",
      "Premiere piece bullion annuelle au monde (1982)",
    ],
  },
  {
    id: "libertad-2oz-argent",
    name: "Libertad 2 Oz Argent",
    metal: "silver",
    weight_oz: 2,
    weight_g: 62.207,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 48.0,
    thickness_mm: 4.0,
    first_year: 1996,
    design_type: "occasional",
    design_changes: [
      { year: 1996, description: "Lancement avec nouveau design" },
    ],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 40,
    face_value: null,
    highlights: ["Format 2oz peu courant sur le marche", "Tirage limite"],
  },
  {
    id: "libertad-5oz-argent",
    name: "Libertad 5 Oz Argent",
    metal: "silver",
    weight_oz: 5,
    weight_g: 155.517,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 65.0,
    thickness_mm: 6.0,
    first_year: 1996,
    design_type: "occasional",
    design_changes: [
      { year: 1996, description: "Lancement avec nouveau design" },
    ],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: null,
    highlights: [
      "Grand format impressionnant",
      "Tirage tres limite (collectionnee)",
    ],
  },
  {
    id: "libertad-1kg-argent",
    name: "Libertad 1 Kg Argent",
    metal: "silver",
    weight_oz: 32.1507,
    weight_g: 1000.0,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 110.0,
    thickness_mm: 12.0,
    first_year: 2008,
    design_type: "occasional",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 30,
    face_value: null,
    highlights: [
      "1 kilogramme d'argent pur",
      "Tirage extremement limite (quelques milliers/an)",
      "Non frappee en 2013 et 2014",
      "Tres recherchee par les collectionneurs",
    ],
  },
  {
    id: "noah-ark-1oz-argent",
    name: "Arche de Noe 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Armenie",
    diameter_mm: 38.6,
    thickness_mm: 3.0,
    first_year: 2011,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 30,
    face_value: "500 AMD",
    highlights: [
      "Frappee par Geiger Edelmetalle (Allemagne)",
      "Prime parmi les plus basses du marche",
      "Piece armenienne mais qualite allemande",
    ],
  },
  {
    id: "lunar-1oz-argent",
    name: "Lunar Series 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 45.6,
    thickness_mm: 2.6,
    first_year: 1999,
    design_type: "annual",
    design_changes: [
      { year: 1999, description: "Lunar Series I" },
      { year: 2008, description: "Lunar Series II" },
      { year: 2020, description: "Lunar Series III" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 45,
    face_value: "1 AUD",
    highlights: [
      "12 animaux du zodiaque chinois (cycle de 12 ans)",
      "Trois series: I (1999), II (2008), III (2020)",
      "Tirages limites, tres collectionnee",
      "Diametre plus grand que les autres 1oz (45.6mm)",
    ],
  },

  // --- Pieces francaises classiques argent ---
  {
    id: "50-francs-hercule-argent",
    name: "50 Francs Hercule Argent",
    metal: "silver",
    weight_oz: 0.8681,
    weight_g: 27.0,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 41.0,
    thickness_mm: 2.5,
    first_year: 1974,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 20,
    estimated_premium_pct: 13,
    face_value: "50 FRF",
    mintage: "46 410 266",
    highlights: [
      "Design Hercule (3 personnages: Liberte, Egalite, Fraternite)",
      "Frappee de 1974 a 1980",
      "TVA 20% (piece demontisee depuis 2002)",
      "Cotation quotidienne CPoR",
    ],
  },
  {
    id: "10-francs-hercule-argent",
    name: "10 Francs Hercule Argent",
    metal: "silver",
    weight_oz: 0.7234,
    weight_g: 22.5,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 37.0,
    thickness_mm: 2.35,
    first_year: 1964,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 20,
    estimated_premium_pct: 12,
    face_value: "10 FRF",
    mintage: "39 088 557",
    highlights: [
      "Meme design Hercule que la 50 Francs",
      "Frappee de 1964 a 1973",
      "Plus accessible que la 50 Francs",
    ],
  },
  {
    id: "5-francs-semeuse-argent",
    name: "5 Francs Semeuse Argent",
    metal: "silver",
    weight_oz: 0.3617,
    weight_g: 12.0,
    purity: 0.835,
    fineness: "835",
    country: "France",
    diameter_mm: 29.0,
    thickness_mm: 2.0,
    first_year: 1960,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 20,
    estimated_premium_pct: 6,
    face_value: "5 FRF",
    mintage: "195 282 126",
    highlights: [
      "Design de la Semeuse (Oscar Roty)",
      "Frappee de 1960 a 1969",
      "Titre 835/1000 (moins pur que Hercule)",
      "Tres liquide, petite denomination",
    ],
  },
  {
    id: "20-francs-turin-argent",
    name: "20 Francs Turin Argent",
    metal: "silver",
    weight_oz: 0.6431,
    weight_g: 20.0,
    purity: 0.68,
    fineness: "680",
    country: "France",
    diameter_mm: 35.0,
    thickness_mm: 2.3,
    first_year: 1929,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 20,
    estimated_premium_pct: 4,
    face_value: "20 FRF",
    mintage: "51 612 474",
    highlights: [
      "Design de Pierre Turin",
      "Titre 680/1000 (alliage billon)",
      "Frappee 1929-1939",
      "Prime tres faible",
    ],
  },
  {
    id: "10-francs-turin-argent",
    name: "10 Francs Turin Argent",
    metal: "silver",
    weight_oz: 0.3215,
    weight_g: 10.0,
    purity: 0.68,
    fineness: "680",
    country: "France",
    diameter_mm: 28.0,
    thickness_mm: 1.9,
    first_year: 1929,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 20,
    estimated_premium_pct: 4,
    face_value: "10 FRF",
    mintage: "98 223 600",
    highlights: [
      "Meme design que la 20 Francs Turin",
      "Titre 680/1000",
      "Frappee 1929-1939",
    ],
  },
  {
    id: "5-francs-hercule-ecu-argent",
    name: "5 Francs Hercule (Ecu) Argent",
    metal: "silver",
    weight_oz: 0.7234,
    weight_g: 25.0,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 37.0,
    thickness_mm: 2.7,
    first_year: 1795,
    design_type: "occasional",
    design_changes: [
      { year: 1795, description: "Union et Force" },
      { year: 1848, description: "Hercule II Republique" },
      { year: 1870, description: "Hercule III Republique" },
    ],
    liquidity: 4,
    vat_fr_pct: 20,
    estimated_premium_pct: 15,
    face_value: "5 FRF",
    highlights: [
      "Piece historique (depuis 1795)",
      "Surnommee 'Ecu' par les numismates",
      "Plusieurs types selon les epoques",
      "Valeur numismatique selon millesime",
    ],
  },

  // --- Pieces internationales complementaires ---
  {
    id: "buffalo-1oz-argent",
    name: "Buffalo 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "USA",
    diameter_mm: 39.0,
    thickness_mm: 2.8,
    first_year: 2001,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 20,
    estimated_premium_pct: 35,
    face_value: null,
    highlights: [
      "Round prive (pas une piece gouvernementale)",
      "Design du nickel Buffalo de 1913",
      "Pas de valeur faciale",
      "Moins liquide que les pieces souveraines",
    ],
  },
  {
    id: "turtle-1oz-argent",
    name: "Niue Turtle 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Niue",
    diameter_mm: 39.0,
    thickness_mm: 3.1,
    first_year: 2014,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 32,
    face_value: "2 NZD",
    highlights: [
      "Frappee par New Zealand Mint",
      "Design de la tortue Hawksbill",
      "Cours legal a Niue (ile du Pacifique)",
      "Prime moderee, design apprecie",
    ],
  },

  // --- Pieces argent manquantes Godot ---
  {
    id: "walking-liberty-1oz-argent",
    name: "Walking Liberty (Silver Eagle) 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.103,
    purity: 0.999,
    fineness: "999",
    country: "USA",
    diameter_mm: 40.6,
    thickness_mm: 2.98,
    first_year: 1986,
    design_type: "occasional",
    design_changes: [
      { year: 2021, description: "Nouveau revers Type 2 (aigle atterrissant)" },
    ],
    liquidity: 5,
    vat_fr_pct: 20,
    estimated_premium_pct: 30,
    face_value: "1 USD",
    highlights: [
      "Piece d'argent d'investissement la plus vendue au monde",
      "Design Walking Liberty d'Adolph Weinman (1916), icone numismatique",
      "Garantie poids et purete par le gouvernement US (US Mint)",
    ],
  },
  {
    id: "hokusai-grande-vague-1oz-argent",
    name: "Hokusai Grande Vague 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.103,
    purity: 0.999,
    fineness: "999",
    country: "Fidji",
    diameter_mm: 38.6,
    thickness_mm: 3.2,
    first_year: 2017,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 20,
    estimated_premium_pct: 60,
    face_value: "1 FJD",
    mintage: "50 000",
    highlights: [
      "Reproduit La Grande Vague de Kanagawa d'Hokusai (1830)",
      "Frappee par Scottsdale Mint (USA), qualite proof-like",
      "Tirage limite (50 000 BU), fort potentiel numismatique",
    ],
  },
  {
    id: "100-francs-argent-1982-2002",
    name: "100 Francs Argent Pantheon (1982-2002)",
    metal: "silver",
    weight_oz: 0.4823,
    weight_g: 15.0,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 31.0,
    thickness_mm: 2.0,
    first_year: 1982,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 20,
    estimated_premium_pct: 40,
    face_value: "100 FRF",
    mintage: "14 850 244",
    highlights: [
      "Derniere piece francaise en argent 900 milliemes, heritage Ve Republique",
      "13.5g d'argent fin (15g x 900 milliemes), valeur metal + collection",
      "Millesimes tardifs (1987-1996) a tirages tres limites, cotes elevees",
    ],
  },
];

export function getCoinById(id: string): Coin | undefined {
  return COINS.find((c) => c.id === id);
}

export function getGoldCoins(): Coin[] {
  return COINS.filter((c) => c.metal === "gold");
}

export function getSilverCoins(): Coin[] {
  return COINS.filter((c) => c.metal === "silver");
}
