import type { Coin } from "@/types";

export const COINS: Coin[] = [
  // =============================================
  // OR - 25 pieces
  // =============================================

  // --- 1 Oz Or ---
  {
    id: "american-buffalo-1oz-or",
    name: "American Buffalo 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "USA",
    diameter_mm: 32.7,
    thickness_mm: 2.95,
    first_year: 2006,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 7.5,
    face_value: "50 USD",
    highlights: [
      "Premiere piece or US en 999.9 (4 neuf)",
      "Design inspire du nickel Buffalo de 1913",
      "Seule piece US en or pur (Eagle est en 22 carats)",
    ],
  },
  {
    id: "american-eagle-1oz-or",
    name: "American Eagle 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 33.93,
    purity: 0.9167,
    fineness: "916.7",
    country: "USA",
    diameter_mm: 32.7,
    thickness_mm: 2.87,
    first_year: 1986,
    design_type: "occasional",
    design_changes: [{ year: 2021, description: "Nouveau revers (aigle)" }],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 8,
    face_value: "50 USD",
    highlights: [
      "Alliage 22 carats (91.67% or, 3% argent, 5.33% cuivre)",
      "Poids total 33.93g pour 1oz d'or pur contenu",
      "Plus resistante aux rayures que les pieces 999.9",
      "Piece or la plus vendue aux USA",
    ],
  },
  {
    id: "britannia-1oz-or",
    name: "Britannia 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 38.61,
    thickness_mm: 2.98,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [
      { year: 2021, description: "Nouveau design securise" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "100 GBP",
    highlights: [
      "Motif de securite anti-contrefacon depuis 2021",
      "Image latente et micro-texte sur le trident",
      "Exoneree de Capital Gains Tax au Royaume-Uni",
    ],
  },
  {
    id: "kangourou-1oz-or",
    name: "Kangourou 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 32.1,
    thickness_mm: 2.65,
    first_year: 1986,
    design_type: "annual",
    design_changes: [
      { year: 1986, description: "Lancement sous le nom Nugget" },
      { year: 1989, description: "Changement pour design Kangourou" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "100 AUD",
    highlights: [
      "Design du kangourou change chaque annee",
      "Anciennement appelee 'Nugget' (1986-1989)",
      "Perth Mint garantit rachat a vie",
    ],
  },
  {
    id: "maple-leaf-1oz-or",
    name: "Maple Leaf 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 30.0,
    thickness_mm: 2.87,
    first_year: 1979,
    design_type: "occasional",
    design_changes: [
      { year: 2013, description: "Ajout micro-gravure securite" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "50 CAD",
    highlights: [
      "Premiere piece bullion 999.9 au monde (1982)",
      "Micro-gravure laser d'une feuille d'erable (visible a la loupe)",
      "Lignes radiales anti-contrefacon depuis 2013",
      "Une des pieces les plus pures du marche",
    ],
  },
  {
    id: "philharmonique-1oz-or",
    name: "Philharmonique 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 37.0,
    thickness_mm: 2.0,
    first_year: 1989,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6.5,
    face_value: "100 EUR",
    highlights: [
      "Seule piece bullion majeure en euros",
      "Pas de portrait de monarque (instruments de musique)",
      "Design inchange depuis 1989",
      "Piece or la plus vendue en Europe",
    ],
  },
  {
    id: "krugerrand-1oz-or",
    name: "Krugerrand 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 33.93,
    purity: 0.9167,
    fineness: "916.7",
    country: "Afrique du Sud",
    diameter_mm: 32.77,
    thickness_mm: 2.84,
    first_year: 1967,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 7,
    face_value: null,
    highlights: [
      "Premiere piece bullion moderne au monde (1967)",
      "Aucune valeur faciale inscrite",
      "Alliage 22 carats avec cuivre (couleur orangee)",
      "Plus de 50 millions d'unites produites",
      "Design inchange depuis 1967",
    ],
  },

  // --- 1/2 Oz Or ---
  {
    id: "britannia-1-2oz-or",
    name: "Britannia 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 27.0,
    thickness_mm: 2.1,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 11,
    face_value: "50 GBP",
  },
  {
    id: "kangourou-1-2oz-or",
    name: "Kangourou 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 25.1,
    thickness_mm: 2.35,
    first_year: 1986,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 10,
    face_value: "50 AUD",
  },
  {
    id: "maple-leaf-1-2oz-or",
    name: "Maple Leaf 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 25.0,
    thickness_mm: 2.23,
    first_year: 1986,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "25 CAD",
  },
  {
    id: "philharmonique-1-2oz-or",
    name: "Philharmonique 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 28.0,
    thickness_mm: 1.6,
    first_year: 1994,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 9,
    face_value: "50 EUR",
  },

  // --- 1/4 Oz Or ---
  {
    id: "britannia-1-4oz-or",
    name: "Britannia 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 22.0,
    thickness_mm: 1.7,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 13,
    face_value: "25 GBP",
  },
  {
    id: "kangourou-1-4oz-or",
    name: "Kangourou 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 20.1,
    thickness_mm: 1.9,
    first_year: 1986,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 14,
    face_value: "25 AUD",
  },
  {
    id: "maple-leaf-1-4oz-or",
    name: "Maple Leaf 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 20.0,
    thickness_mm: 1.78,
    first_year: 1982,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: "10 CAD",
  },
  {
    id: "philharmonique-1-4oz-or",
    name: "Philharmonique 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 22.0,
    thickness_mm: 1.2,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: "25 EUR",
  },

  // --- 1/10 Oz Or ---
  {
    id: "britannia-1-10oz-or",
    name: "Britannia 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Royaume-Uni",
    diameter_mm: 16.5,
    thickness_mm: 1.3,
    first_year: 1987,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 21,
    face_value: "10 GBP",
  },
  {
    id: "kangourou-1-10oz-or",
    name: "Kangourou 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 16.1,
    thickness_mm: 1.4,
    first_year: 1986,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 20,
    face_value: "15 AUD",
  },
  {
    id: "maple-leaf-1-10oz-or",
    name: "Maple Leaf 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 16.0,
    thickness_mm: 1.22,
    first_year: 1982,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 18,
    face_value: "5 CAD",
  },
  {
    id: "philharmonique-1-10oz-or",
    name: "Philharmonique 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.9999,
    fineness: "999.9",
    country: "Autriche",
    diameter_mm: 16.0,
    thickness_mm: 0.9,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 18,
    face_value: "10 EUR",
  },

  // --- Fractionnelles & Panda Or ---
  {
    id: "maple-leaf-1-20oz-or",
    name: "Maple Leaf 1/20 Oz Or",
    metal: "gold",
    weight_oz: 0.05,
    weight_g: 1.56,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 14.1,
    thickness_mm: 0.92,
    first_year: 1993,
    design_type: "occasional",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 36,
    face_value: "1 CAD",
    highlights: [
      "Plus petite Maple Leaf disponible",
      "Prime elevee due a la taille",
      "Ideale pour cadeau ou petit budget",
    ],
  },
  {
    id: "panda-30g-or",
    name: "Panda Or 30g",
    metal: "gold",
    weight_oz: 0.9645,
    weight_g: 30.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 32.0,
    thickness_mm: 2.4,
    first_year: 1982,
    design_type: "annual",
    design_changes: [{ year: 2016, description: "Passage de 1oz a 30g" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 7,
    face_value: "500 CNY",
    highlights: [
      "Design du panda change chaque annee (tres collectionne)",
      "Passage de l'once troy (31.1g) au gramme (30g) en 2016",
      "Seule piece bullion majeure en grammes",
      "Tres populaire aupres des collectionneurs asiatiques",
    ],
  },
  {
    id: "panda-15g-or",
    name: "Panda Or 15g",
    metal: "gold",
    weight_oz: 0.4823,
    weight_g: 15.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 27.0,
    thickness_mm: 1.85,
    first_year: 1982,
    design_type: "annual",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "200 CNY",
  },
  {
    id: "panda-8g-or",
    name: "Panda Or 8g",
    metal: "gold",
    weight_oz: 0.2572,
    weight_g: 8.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 22.0,
    thickness_mm: 1.5,
    first_year: 1982,
    design_type: "annual",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 13,
    face_value: "100 CNY",
  },

  // --- Pieces classiques cotees ---
  {
    id: "napoleon-20f-or",
    name: "Napoleon 20 Francs Or",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.45,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 21.0,
    thickness_mm: 1.3,
    first_year: 1803,
    design_type: "occasional",
    design_changes: [
      { year: 1803, description: "Napoleon Empereur" },
      { year: 1807, description: "Tete lauree" },
      { year: 1852, description: "Napoleon III" },
      { year: 1899, description: "Marianne Coq" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6,
    face_value: "20 FRF",
    highlights: [
      "Piece d'or francaise la plus echangee",
      "Cotation quotidienne (CPoR Devises)",
      "Nombreuses variantes (Coq, Napoleon III, etc.)",
      "Exoneree de TVA et plus-values apres 22 ans",
      "Format standardise de l'Union Latine",
    ],
  },
  {
    id: "souverain-or",
    name: "Souverain Or",
    metal: "gold",
    weight_oz: 0.2354,
    weight_g: 7.98,
    purity: 0.9167,
    fineness: "916.7",
    country: "Royaume-Uni",
    diameter_mm: 22.05,
    thickness_mm: 1.52,
    first_year: 1817,
    design_type: "occasional",
    design_changes: [
      { year: 1817, description: "George III" },
      { year: 1893, description: "Victoria Old Head" },
      { year: 1902, description: "Edward VII" },
      { year: 1911, description: "George V" },
      { year: 1937, description: "George VI" },
      { year: 1957, description: "Elizabeth II" },
      { year: 2023, description: "Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 8,
    face_value: "1 GBP",
    highlights: [
      "Plus de 200 ans d'histoire",
      "Design Saint-Georges terrassant le dragon",
      "Nombreux millesimes et ateliers de frappe",
      "Exoneree de CGT au Royaume-Uni",
      "Tres liquide sur le marche europeen",
    ],
  },
  {
    id: "20-francs-suisse-or",
    name: "20 Francs Suisse Or (Vreneli)",
    metal: "gold",
    weight_oz: 0.1867,
    weight_g: 6.45,
    purity: 0.9,
    fineness: "900",
    country: "Suisse",
    diameter_mm: 21.0,
    thickness_mm: 1.25,
    first_year: 1897,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6,
    face_value: "20 CHF",
    highlights: [
      "Surnommee 'Vreneli' (petit visage de femme)",
      "Meme poids et titre que le Napoleon 20F",
      "Membre de l'Union Latine (interchangeable)",
      "Faible prime, excellente liquidite",
    ],
  },

  // --- Libertad Or (Mexique) ---
  {
    id: "libertad-1oz-or",
    name: "Libertad 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 34.5,
    thickness_mm: 2.69,
    first_year: 1981,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: null,
    highlights: [
      "Frappee par Casa de Moneda de Mexico (plus vieille menthe des Ameriques)",
      "Design iconique : Victoire Ailee + volcans Popocatepetl et Iztaccihuatl",
      "Pas de valeur faciale (cours legal sans denomination)",
      "Tirage limite, plus rare que Maple Leaf ou Eagle",
    ],
  },
  {
    id: "libertad-1-2oz-or",
    name: "Libertad 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    weight_g: 15.5517,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 29.0,
    thickness_mm: 2.17,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: null,
    highlights: [
      "Format fractionnel populaire",
      "Meme design que la 1oz",
      "Tirage tres limite",
    ],
  },
  {
    id: "libertad-1-4oz-or",
    name: "Libertad 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    weight_g: 7.7758,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 23.0,
    thickness_mm: 1.78,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 18,
    face_value: null,
    highlights: [
      "Petit format accessible",
      "Prime plus elevee que les 1oz",
      "Collectionnee pour sa rarete",
    ],
  },
  {
    id: "libertad-1-10oz-or",
    name: "Libertad 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    weight_g: 3.1103,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 16.0,
    thickness_mm: 1.19,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 25,
    face_value: null,
    highlights: [
      "Format ideal pour debuter",
      "Prime elevee sur petits formats",
      "Tres recherchee des collectionneurs",
    ],
  },
  {
    id: "libertad-1-20oz-or",
    name: "Libertad 1/20 Oz Or",
    metal: "gold",
    weight_oz: 0.05,
    weight_g: 1.5551,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 13.0,
    thickness_mm: 0.85,
    first_year: 1991,
    design_type: "fixed",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: null,
    highlights: [
      "Plus petite Libertad or disponible",
      "Prime tres elevee",
      "Plutot pour collectionneurs que investisseurs",
    ],
  },

  // =============================================
  // ARGENT - 25 pieces
  // =============================================

  // --- 1 Oz Argent bullion moderne ---
  {
    id: "maple-leaf-1oz-argent",
    name: "Maple Leaf 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Canada",
    diameter_mm: 38.0,
    thickness_mm: 3.29,
    first_year: 1988,
    design_type: "occasional",
    design_changes: [
      { year: 2014, description: "Ajout micro-gravure securite" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: "5 CAD",
    highlights: [
      "Purete 999.9 (4 neuf) - la plus pure du marche",
      "Micro-gravure laser et lignes radiales anti-contrefacon",
      "Une des pieces argent les plus vendues au monde",
    ],
  },
  {
    id: "philharmonique-1oz-argent",
    name: "Vienna Philharmonic 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Autriche",
    diameter_mm: 37.0,
    thickness_mm: 3.2,
    first_year: 2008,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 34,
    face_value: "1.50 EUR",
    highlights: [
      "Version argent lancee en 2008 (or depuis 1989)",
      "Seule piece bullion argent en euros",
      "Design identique a la version or",
    ],
  },
  {
    id: "kangourou-1oz-argent",
    name: "Kangourou 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 40.6,
    thickness_mm: 4.0,
    first_year: 2016,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: "1 AUD",
    highlights: [
      "Lancee en 2016 (plus recente que la version or)",
      "Design du kangourou change chaque annee",
      "Purete 999.9 comme la Maple Leaf",
    ],
  },
  {
    id: "britannia-1oz-argent",
    name: "Britannia 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Royaume-Uni",
    diameter_mm: 38.61,
    thickness_mm: 3.0,
    first_year: 1997,
    design_type: "occasional",
    design_changes: [
      { year: 2021, description: "Nouveau design securise" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 34,
    face_value: "2 GBP",
    highlights: [
      "Elements de securite avances depuis 2021",
      "Image latente et micro-texte sur le trident",
      "Exoneree de CGT au Royaume-Uni",
    ],
  },
  {
    id: "american-eagle-1oz-argent",
    name: "American Eagle 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "USA",
    diameter_mm: 40.6,
    thickness_mm: 2.98,
    first_year: 1986,
    design_type: "occasional",
    design_changes: [{ year: 2021, description: "Nouveau revers (aigle)" }],
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 38,
    face_value: "1 USD",
    highlights: [
      "Piece argent la plus vendue au monde",
      "Design Walking Liberty (avers) depuis 1986",
      "Nouveau revers avec aigle en vol depuis 2021",
      "Prime plus elevee que les concurrentes",
    ],
  },
  {
    id: "krugerrand-1oz-argent",
    name: "Krugerrand 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Afrique du Sud",
    diameter_mm: 38.725,
    thickness_mm: 3.0,
    first_year: 2017,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 33,
    face_value: null,
    highlights: [
      "Lancee en 2017 pour les 50 ans du Krugerrand or",
      "Meme design que la version or",
      "Pas de valeur faciale (comme la version or)",
    ],
  },
  {
    id: "panda-30g-argent",
    name: "China Panda 30g Argent",
    metal: "silver",
    weight_oz: 0.9645,
    weight_g: 30.0,
    purity: 0.999,
    fineness: "999",
    country: "Chine",
    diameter_mm: 40.0,
    thickness_mm: 2.98,
    first_year: 1983,
    design_type: "annual",
    design_changes: [{ year: 2016, description: "Passage de 1oz a 30g" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 38,
    face_value: "10 CNY",
    highlights: [
      "Design du panda change chaque annee",
      "Passage de 1oz a 30g en 2016",
      "Tres recherchee par les collectionneurs",
    ],
  },
  {
    id: "kookaburra-1oz-argent",
    name: "Kookaburra 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Australie",
    diameter_mm: 40.6,
    thickness_mm: 4.0,
    first_year: 1990,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 43,
    face_value: "1 AUD",
    highlights: [
      "Design du martin-chasseur change chaque annee",
      "Premiere piece australienne a design annuel",
      "Tirages limites (collectionnee par millesime)",
    ],
  },
  {
    id: "koala-1oz-argent",
    name: "Koala 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Australie",
    diameter_mm: 40.6,
    thickness_mm: 4.0,
    first_year: 2007,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 43,
    face_value: "1 AUD",
    highlights: [
      "Design du koala change chaque annee",
      "Lancee en 2007 (plus recente que Kookaburra)",
      "Tirages limites, recherchee par les collectionneurs",
    ],
  },
  {
    id: "libertad-1-20oz-argent",
    name: "Libertad 1/20 Oz Argent",
    metal: "silver",
    weight_oz: 0.05,
    weight_g: 1.555,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 16.0,
    thickness_mm: 1.0,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 120,
    face_value: null,
    highlights: [
      "Plus petite Libertad disponible",
      "Tirage tres limite",
      "Prime tres elevee due a la rarete",
    ],
  },
  {
    id: "libertad-1-10oz-argent",
    name: "Libertad 1/10 Oz Argent",
    metal: "silver",
    weight_oz: 0.1,
    weight_g: 3.11,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 20.0,
    thickness_mm: 1.3,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 80,
    face_value: null,
  },
  {
    id: "libertad-1-4oz-argent",
    name: "Libertad 1/4 Oz Argent",
    metal: "silver",
    weight_oz: 0.25,
    weight_g: 7.78,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 27.0,
    thickness_mm: 2.0,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 60,
    face_value: null,
  },
  {
    id: "libertad-1-2oz-argent",
    name: "Libertad 1/2 Oz Argent",
    metal: "silver",
    weight_oz: 0.5,
    weight_g: 15.55,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 33.0,
    thickness_mm: 2.5,
    first_year: 1992,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 50,
    face_value: null,
  },
  {
    id: "libertad-1oz-argent",
    name: "Libertad 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 40.0,
    thickness_mm: 3.0,
    first_year: 1982,
    design_type: "occasional",
    design_changes: [{ year: 1996, description: "Nouveau design revers" }],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 45,
    face_value: null,
    highlights: [
      "Aucune valeur faciale (unique parmi les pieces bullion)",
      "Valeur legale = cours du metal (fluctue quotidiennement)",
      "Tirage tres limite (prime elevee)",
      "Design de l'Ange de l'Independance",
      "Garantie par Banco de Mexico",
      "Premiere piece bullion annuelle au monde (1982)",
    ],
  },
  {
    id: "libertad-2oz-argent",
    name: "Libertad 2 Oz Argent",
    metal: "silver",
    weight_oz: 2,
    weight_g: 62.207,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 48.0,
    thickness_mm: 4.0,
    first_year: 1996,
    design_type: "occasional",
    design_changes: [
      { year: 1996, description: "Lancement avec nouveau design" },
    ],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 40,
    face_value: null,
    highlights: ["Format 2oz peu courant sur le marche", "Tirage limite"],
  },
  {
    id: "libertad-5oz-argent",
    name: "Libertad 5 Oz Argent",
    metal: "silver",
    weight_oz: 5,
    weight_g: 155.517,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 65.0,
    thickness_mm: 6.0,
    first_year: 1996,
    design_type: "occasional",
    design_changes: [
      { year: 1996, description: "Lancement avec nouveau design" },
    ],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: null,
    highlights: [
      "Grand format impressionnant",
      "Tirage tres limite (collectionnee)",
    ],
  },
  {
    id: "libertad-1kg-argent",
    name: "Libertad 1 Kg Argent",
    metal: "silver",
    weight_oz: 32.1507,
    weight_g: 1000.0,
    purity: 0.999,
    fineness: "999",
    country: "Mexique",
    diameter_mm: 110.0,
    thickness_mm: 12.0,
    first_year: 2008,
    design_type: "occasional",
    liquidity: 2,
    vat_fr_pct: 0,
    estimated_premium_pct: 30,
    face_value: null,
    highlights: [
      "1 kilogramme d'argent pur",
      "Tirage extremement limite (quelques milliers/an)",
      "Non frappee en 2013 et 2014",
      "Tres recherchee par les collectionneurs",
    ],
  },
  {
    id: "noah-ark-1oz-argent",
    name: "Arche de Noe 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Armenie",
    diameter_mm: 38.6,
    thickness_mm: 3.0,
    first_year: 2011,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 30,
    face_value: "500 AMD",
    highlights: [
      "Frappee par Geiger Edelmetalle (Allemagne)",
      "Prime parmi les plus basses du marche",
      "Piece armenienne mais qualite allemande",
    ],
  },
  {
    id: "lunar-1oz-argent",
    name: "Lunar Series 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.9999,
    fineness: "999.9",
    country: "Australie",
    diameter_mm: 45.6,
    thickness_mm: 2.6,
    first_year: 1999,
    design_type: "annual",
    design_changes: [
      { year: 1999, description: "Lunar Series I" },
      { year: 2008, description: "Lunar Series II" },
      { year: 2020, description: "Lunar Series III" },
      { year: 2023, description: "Avers Charles III" },
    ],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 45,
    face_value: "1 AUD",
    highlights: [
      "12 animaux du zodiaque chinois (cycle de 12 ans)",
      "Trois series: I (1999), II (2008), III (2020)",
      "Tirages limites, tres collectionnee",
      "Diametre plus grand que les autres 1oz (45.6mm)",
    ],
  },

  // --- 1 Kg Argent ---
  {
    id: "kookaburra-1kg-argent",
    name: "Kookaburra 1 Kg Argent",
    metal: "silver",
    weight_oz: 32.1507,
    weight_g: 1000.0,
    purity: 0.999,
    fineness: "999",
    country: "Australie",
    diameter_mm: 100.6,
    thickness_mm: 14.6,
    first_year: 1992,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 26,
    face_value: "30 AUD",
    highlights: [
      "1 kilogramme d'argent pur",
      "Design annuel comme la version 1oz",
      "Format populaire pour gros investisseurs",
    ],
  },
  {
    id: "koala-1kg-argent",
    name: "Koala 1 Kg Argent",
    metal: "silver",
    weight_oz: 32.1507,
    weight_g: 1000.0,
    purity: 0.999,
    fineness: "999",
    country: "Australie",
    diameter_mm: 100.6,
    thickness_mm: 14.0,
    first_year: 2008,
    design_type: "annual",
    design_changes: [{ year: 2023, description: "Avers Charles III" }],
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 26,
    face_value: "30 AUD",
  },

  // --- Pieces francaises classiques argent ---
  {
    id: "50-francs-hercule-argent",
    name: "50 Francs Hercule Argent",
    metal: "silver",
    weight_oz: 0.8681,
    weight_g: 27.0,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 41.0,
    thickness_mm: 2.5,
    first_year: 1974,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 13,
    face_value: "50 FRF",
    highlights: [
      "Design Hercule (3 personnages: Liberte, Egalite, Fraternite)",
      "Frappee de 1974 a 1980",
      "Exoneree de TVA (ancien cours legal)",
      "Cotation quotidienne CPoR",
    ],
  },
  {
    id: "10-francs-hercule-argent",
    name: "10 Francs Hercule Argent",
    metal: "silver",
    weight_oz: 0.7234,
    weight_g: 22.5,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 37.0,
    thickness_mm: 2.35,
    first_year: 1964,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 12,
    face_value: "10 FRF",
    highlights: [
      "Meme design Hercule que la 50 Francs",
      "Frappee de 1964 a 1973",
      "Plus accessible que la 50 Francs",
    ],
  },
  {
    id: "5-francs-semeuse-argent",
    name: "5 Francs Semeuse Argent",
    metal: "silver",
    weight_oz: 0.3617,
    weight_g: 12.0,
    purity: 0.835,
    fineness: "835",
    country: "France",
    diameter_mm: 29.0,
    thickness_mm: 2.0,
    first_year: 1960,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 6,
    face_value: "5 FRF",
    highlights: [
      "Design de la Semeuse (Oscar Roty)",
      "Frappee de 1960 a 1969",
      "Titre 835/1000 (moins pur que Hercule)",
      "Tres liquide, petite denomination",
    ],
  },
  {
    id: "100-francs-pantheon-argent",
    name: "100 Francs Pantheon Argent",
    metal: "silver",
    weight_oz: 0.4823,
    weight_g: 15.0,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 31.0,
    thickness_mm: 2.2,
    first_year: 1982,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 7,
    face_value: "100 FRF",
    highlights: [
      "Design du Pantheon de Paris",
      "Frappee de 1982 a 2001",
      "Derniere piece argent francaise a cours legal",
    ],
  },
  {
    id: "20-francs-turin-argent",
    name: "20 Francs Turin Argent",
    metal: "silver",
    weight_oz: 0.6431,
    weight_g: 20.0,
    purity: 0.68,
    fineness: "680",
    country: "France",
    diameter_mm: 35.0,
    thickness_mm: 2.3,
    first_year: 1929,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 4,
    face_value: "20 FRF",
    highlights: [
      "Design de Pierre Turin",
      "Titre 680/1000 (alliage billon)",
      "Frappee 1929-1939",
      "Prime tres faible",
    ],
  },
  {
    id: "10-francs-turin-argent",
    name: "10 Francs Turin Argent",
    metal: "silver",
    weight_oz: 0.3215,
    weight_g: 10.0,
    purity: 0.68,
    fineness: "680",
    country: "France",
    diameter_mm: 28.0,
    thickness_mm: 1.9,
    first_year: 1929,
    design_type: "fixed",
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 4,
    face_value: "10 FRF",
    highlights: [
      "Meme design que la 20 Francs Turin",
      "Titre 680/1000",
      "Frappee 1929-1939",
    ],
  },
  {
    id: "5-francs-hercule-ecu-argent",
    name: "5 Francs Hercule (Ecu) Argent",
    metal: "silver",
    weight_oz: 0.7234,
    weight_g: 25.0,
    purity: 0.9,
    fineness: "900",
    country: "France",
    diameter_mm: 37.0,
    thickness_mm: 2.7,
    first_year: 1795,
    design_type: "occasional",
    design_changes: [
      { year: 1795, description: "Union et Force" },
      { year: 1848, description: "Hercule II Republique" },
      { year: 1870, description: "Hercule III Republique" },
    ],
    liquidity: 4,
    vat_fr_pct: 0,
    estimated_premium_pct: 15,
    face_value: "5 FRF",
    highlights: [
      "Piece historique (depuis 1795)",
      "Surnommee 'Ecu' par les numismates",
      "Plusieurs types selon les epoques",
      "Valeur numismatique selon millesime",
    ],
  },

  // --- Lingot argent ---
  {
    id: "lingot-1kg-argent",
    name: "Lingot Argent 1 Kg",
    metal: "silver",
    weight_oz: 32.1507,
    weight_g: 1000.0,
    purity: 0.999,
    fineness: "999",
    country: "International",
    diameter_mm: 0,
    thickness_mm: 0,
    first_year: 1900,
    design_type: "fixed",
    liquidity: 5,
    vat_fr_pct: 0,
    estimated_premium_pct: 11,
    face_value: null,
    highlights: [
      "Format rectangulaire (pas de diametre)",
      "Prime la plus basse du marche argent",
      "Pas de valeur numismatique",
      "Ideal pour investissement pur",
    ],
  },

  // --- Pieces internationales complementaires ---
  {
    id: "buffalo-1oz-argent",
    name: "Buffalo 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "USA",
    diameter_mm: 39.0,
    thickness_mm: 2.8,
    first_year: 2001,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 35,
    face_value: null,
    highlights: [
      "Round prive (pas une piece gouvernementale)",
      "Design du nickel Buffalo de 1913",
      "Pas de valeur faciale",
      "Moins liquide que les pieces souveraines",
    ],
  },
  {
    id: "turtle-1oz-argent",
    name: "Niue Turtle 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    weight_g: 31.1035,
    purity: 0.999,
    fineness: "999",
    country: "Niue",
    diameter_mm: 39.0,
    thickness_mm: 3.1,
    first_year: 2014,
    design_type: "fixed",
    liquidity: 3,
    vat_fr_pct: 0,
    estimated_premium_pct: 32,
    face_value: "2 NZD",
    highlights: [
      "Frappee par New Zealand Mint",
      "Design de la tortue Hawksbill",
      "Cours legal a Niue (ile du Pacifique)",
      "Prime moderee, design apprecie",
    ],
  },
];

export function getCoinById(id: string): Coin | undefined {
  return COINS.find((c) => c.id === id);
}

export function getGoldCoins(): Coin[] {
  return COINS.filter((c) => c.metal === "gold");
}

export function getSilverCoins(): Coin[] {
  return COINS.filter((c) => c.metal === "silver");
}
