import type { Coin } from "@/types";

export const COINS: Coin[] = [
  // =============================================
  // OR - 25 pieces
  // =============================================

  // --- 1 Oz Or ---
  {
    id: "american-buffalo-1oz-or",
    name: "American Buffalo 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    purity: 0.9999,
    country: "USA",
    estimated_premium_pct: 7.5,
  },
  {
    id: "american-eagle-1oz-or",
    name: "American Eagle 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    purity: 0.9167,
    country: "USA",
    estimated_premium_pct: 8,
  },
  {
    id: "britannia-1oz-or",
    name: "Britannia 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    purity: 0.9999,
    country: "Royaume-Uni",
    estimated_premium_pct: 6.5,
  },
  {
    id: "kangourou-1oz-or",
    name: "Kangourou 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    purity: 0.9999,
    country: "Australie",
    estimated_premium_pct: 6.5,
  },
  {
    id: "maple-leaf-1oz-or",
    name: "Maple Leaf 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    purity: 0.9999,
    country: "Canada",
    estimated_premium_pct: 6.5,
  },
  {
    id: "philharmonique-1oz-or",
    name: "Philharmonique 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    purity: 0.9999,
    country: "Autriche",
    estimated_premium_pct: 6.5,
  },
  {
    id: "krugerrand-1oz-or",
    name: "Krugerrand 1 Oz Or",
    metal: "gold",
    weight_oz: 1,
    purity: 0.9167,
    country: "Afrique du Sud",
    estimated_premium_pct: 7,
  },

  // --- 1/2 Oz Or ---
  {
    id: "britannia-1-2oz-or",
    name: "Britannia 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    purity: 0.9999,
    country: "Royaume-Uni",
    estimated_premium_pct: 11,
  },
  {
    id: "kangourou-1-2oz-or",
    name: "Kangourou 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    purity: 0.9999,
    country: "Australie",
    estimated_premium_pct: 10,
  },
  {
    id: "maple-leaf-1-2oz-or",
    name: "Maple Leaf 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    purity: 0.9999,
    country: "Canada",
    estimated_premium_pct: 12,
  },
  {
    id: "philharmonique-1-2oz-or",
    name: "Philharmonique 1/2 Oz Or",
    metal: "gold",
    weight_oz: 0.5,
    purity: 0.9999,
    country: "Autriche",
    estimated_premium_pct: 9,
  },

  // --- 1/4 Oz Or ---
  {
    id: "britannia-1-4oz-or",
    name: "Britannia 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    purity: 0.9999,
    country: "Royaume-Uni",
    estimated_premium_pct: 13,
  },
  {
    id: "kangourou-1-4oz-or",
    name: "Kangourou 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    purity: 0.9999,
    country: "Australie",
    estimated_premium_pct: 14,
  },
  {
    id: "maple-leaf-1-4oz-or",
    name: "Maple Leaf 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    purity: 0.9999,
    country: "Canada",
    estimated_premium_pct: 15,
  },
  {
    id: "philharmonique-1-4oz-or",
    name: "Philharmonique 1/4 Oz Or",
    metal: "gold",
    weight_oz: 0.25,
    purity: 0.9999,
    country: "Autriche",
    estimated_premium_pct: 15,
  },

  // --- 1/10 Oz Or ---
  {
    id: "britannia-1-10oz-or",
    name: "Britannia 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    purity: 0.9999,
    country: "Royaume-Uni",
    estimated_premium_pct: 21,
  },
  {
    id: "kangourou-1-10oz-or",
    name: "Kangourou 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    purity: 0.9999,
    country: "Australie",
    estimated_premium_pct: 20,
  },
  {
    id: "maple-leaf-1-10oz-or",
    name: "Maple Leaf 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    purity: 0.9999,
    country: "Canada",
    estimated_premium_pct: 18,
  },
  {
    id: "philharmonique-1-10oz-or",
    name: "Philharmonique 1/10 Oz Or",
    metal: "gold",
    weight_oz: 0.1,
    purity: 0.9999,
    country: "Autriche",
    estimated_premium_pct: 18,
  },

  // --- Fractionnelles & Panda Or ---
  {
    id: "maple-leaf-1-20oz-or",
    name: "Maple Leaf 1/20 Oz Or",
    metal: "gold",
    weight_oz: 0.05,
    purity: 0.9999,
    country: "Canada",
    estimated_premium_pct: 36,
  },
  {
    id: "panda-30g-or",
    name: "Panda Or 30g",
    metal: "gold",
    weight_oz: 0.9645,
    purity: 0.999,
    country: "Chine",
    estimated_premium_pct: 7,
  },
  {
    id: "panda-15g-or",
    name: "Panda Or 15g",
    metal: "gold",
    weight_oz: 0.4823,
    purity: 0.999,
    country: "Chine",
    estimated_premium_pct: 12,
  },
  {
    id: "panda-8g-or",
    name: "Panda Or 8g",
    metal: "gold",
    weight_oz: 0.2572,
    purity: 0.999,
    country: "Chine",
    estimated_premium_pct: 13,
  },

  // --- Pieces classiques cotees ---
  {
    id: "napoleon-20f-or",
    name: "Napoleon 20 Francs Or",
    metal: "gold",
    weight_oz: 0.1867,
    purity: 0.9,
    country: "France",
    estimated_premium_pct: 6,
  },
  {
    id: "souverain-or",
    name: "Souverain Or",
    metal: "gold",
    weight_oz: 0.2354,
    purity: 0.9167,
    country: "Royaume-Uni",
    estimated_premium_pct: 8,
  },
  {
    id: "20-francs-suisse-or",
    name: "20 Francs Suisse Or (Vreneli)",
    metal: "gold",
    weight_oz: 0.1867,
    purity: 0.9,
    country: "Suisse",
    estimated_premium_pct: 6,
  },

  // =============================================
  // ARGENT - 25 pieces
  // =============================================

  // --- 1 Oz Argent bullion moderne ---
  {
    id: "maple-leaf-1oz-argent",
    name: "Maple Leaf 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.9999,
    country: "Canada",
    estimated_premium_pct: 35,
  },
  {
    id: "philharmonique-1oz-argent",
    name: "Vienna Philharmonic 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Autriche",
    estimated_premium_pct: 34,
  },
  {
    id: "kangourou-1oz-argent",
    name: "Kangourou 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.9999,
    country: "Australie",
    estimated_premium_pct: 35,
  },
  {
    id: "britannia-1oz-argent",
    name: "Britannia 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Royaume-Uni",
    estimated_premium_pct: 34,
  },
  {
    id: "american-eagle-1oz-argent",
    name: "American Eagle 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "USA",
    estimated_premium_pct: 38,
  },
  {
    id: "krugerrand-1oz-argent",
    name: "Krugerrand 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Afrique du Sud",
    estimated_premium_pct: 33,
  },
  {
    id: "panda-30g-argent",
    name: "China Panda 30g Argent",
    metal: "silver",
    weight_oz: 0.9645,
    purity: 0.999,
    country: "Chine",
    estimated_premium_pct: 38,
  },
  {
    id: "kookaburra-1oz-argent",
    name: "Kookaburra 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Australie",
    estimated_premium_pct: 43,
  },
  {
    id: "koala-1oz-argent",
    name: "Koala 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Australie",
    estimated_premium_pct: 43,
  },
  {
    id: "libertad-1oz-argent",
    name: "Libertad 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Mexique",
    estimated_premium_pct: 45,
  },
  {
    id: "noah-ark-1oz-argent",
    name: "Arche de Noe 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Armenie",
    estimated_premium_pct: 30,
  },
  {
    id: "lunar-1oz-argent",
    name: "Lunar Series 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.9999,
    country: "Australie",
    estimated_premium_pct: 45,
  },

  // --- 1 Kg Argent ---
  {
    id: "kookaburra-1kg-argent",
    name: "Kookaburra 1 Kg Argent",
    metal: "silver",
    weight_oz: 32.1507,
    purity: 0.999,
    country: "Australie",
    estimated_premium_pct: 26,
  },
  {
    id: "koala-1kg-argent",
    name: "Koala 1 Kg Argent",
    metal: "silver",
    weight_oz: 32.1507,
    purity: 0.999,
    country: "Australie",
    estimated_premium_pct: 26,
  },

  // --- Pieces francaises classiques argent ---
  {
    id: "50-francs-hercule-argent",
    name: "50 Francs Hercule Argent",
    metal: "silver",
    weight_oz: 0.8681,
    purity: 0.9,
    country: "France",
    estimated_premium_pct: 13,
  },
  {
    id: "10-francs-hercule-argent",
    name: "10 Francs Hercule Argent",
    metal: "silver",
    weight_oz: 0.7234,
    purity: 0.9,
    country: "France",
    estimated_premium_pct: 12,
  },
  {
    id: "5-francs-semeuse-argent",
    name: "5 Francs Semeuse Argent",
    metal: "silver",
    weight_oz: 0.3617,
    purity: 0.835,
    country: "France",
    estimated_premium_pct: 6,
  },
  {
    id: "100-francs-pantheon-argent",
    name: "100 Francs Pantheon Argent",
    metal: "silver",
    weight_oz: 0.4823,
    purity: 0.9,
    country: "France",
    estimated_premium_pct: 7,
  },
  {
    id: "20-francs-turin-argent",
    name: "20 Francs Turin Argent",
    metal: "silver",
    weight_oz: 0.6431,
    purity: 0.68,
    country: "France",
    estimated_premium_pct: 4,
  },
  {
    id: "10-francs-turin-argent",
    name: "10 Francs Turin Argent",
    metal: "silver",
    weight_oz: 0.3215,
    purity: 0.68,
    country: "France",
    estimated_premium_pct: 4,
  },
  {
    id: "5-francs-hercule-ecu-argent",
    name: "5 Francs Hercule (Ecu) Argent",
    metal: "silver",
    weight_oz: 0.7234,
    purity: 0.9,
    country: "France",
    estimated_premium_pct: 15,
  },

  // --- Lingot argent ---
  {
    id: "lingot-1kg-argent",
    name: "Lingot Argent 1 Kg",
    metal: "silver",
    weight_oz: 32.1507,
    purity: 0.999,
    country: "International",
    estimated_premium_pct: 11,
  },

  // --- Pieces internationales complementaires ---
  {
    id: "buffalo-1oz-argent",
    name: "Buffalo 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "USA",
    estimated_premium_pct: 35,
  },
  {
    id: "turtle-1oz-argent",
    name: "Niue Turtle 1 Oz Argent",
    metal: "silver",
    weight_oz: 1,
    purity: 0.999,
    country: "Niue",
    estimated_premium_pct: 32,
  },
];

export function getCoinById(id: string): Coin | undefined {
  return COINS.find((c) => c.id === id);
}

export function getGoldCoins(): Coin[] {
  return COINS.filter((c) => c.metal === "gold");
}

export function getSilverCoins(): Coin[] {
  return COINS.filter((c) => c.metal === "silver");
}
